#!/bin/bash

PREF=$HOME/Dropbox/tw
DIRS='08 emem ira200'
DIRS='cat_balanced'

c=0.8
s=0.8

echo "# C=${c}, sigma=${s}"
for d in $DIRS; do
  echo '##' $d
  ./svm/test-cross.sh $PREF/$d/f $PREF/$d/h $c $s
done
