#!/bin/bash

PREF=$HOME/Dropbox/tw
DIRS='08 emem ira200'
EMS='null yor ika'

for d in $DIRS; do
  for e in $EMS; do
    echo $d $e
    ./svm/test-cross.sh $e $PREF/$d/f $PREF/$d/h | grep -A 3 "Positive" | tail -n 3
  done
done
