#!/bin/sh

UNITS=$1
EXPORT=$2

cat ./template.html > $EXPORT
cat ${UNITS} | \
  sed -e 's/__EOT__/<\/div><div class=tw>/' \
      -e 's/<text>/<span>/' \
      -e 's/<\/text>/<\/span>/' \
      -e 's/<icon>/<span>/' \
      -e 's/<\/icon>/<\/span>/' \
  >> ${EXPORT}
